### PR TITLE
Move directory to /switch

### PR DESCRIPTION
**Pull request by newget**
the root of sdcard could be quite a mess.
Please move it to under the /switch directory.

https://www.reddit.com/r/SwitchHacks/comments/aax1ub/goldleaf_v01_has_released/ecvy73a/
Someone else's comment on reddit.

### CODE REVIEW

**Comment by XorTroll** [comment]
Give a me a really good reason to move it there, as I personally prefer to have it on the root.

**Comment by newget** [comment]
I think this is cleaner way to store files.
Executable nro file and all other stuff in same folder, not separated.

Most of switch homebrews are using "/switch/homebrewname" if they have something to store including setting file and images.

If we have to access folder very frequently, it must be on the root. But I think this is not the case.

**Comment by Crissal1995** [comment]
What about nsp users of Gleaf? There is no need to put files into switch folder (and btw already atmosphere, hekate - bootloader and qlaunch themes take place into root sd, it's a obvious choice)

**Comment by smurfhunter** [comment]
@Crissal1995, it being an NSP changes nothing. It still adds clutter to the root of the SD card.

**Comment by UnicornsOnLSD** [comment]
The NRO version should definitely move to /switch. It's nice to have everything together. Atmosphere's and Hekate's placements make sense since they are very important parts of the Switch homebrew system.

**Comment by Aeuko** [comment]
Yes, in order to be neat, please move him to the switch directory

**Comment by ELY3M** [comment]
I agree

**Comment by XorTroll** [comment]
Made a poll in Discord, results will tell.

**Comment by XorTroll** [comment]
However, since this PR is old will do the changes myself it it gets moved, so closing it.

**Pull request closed without merging**
