### PR TITLE
Re update kr.json

### PR DESCRIPTION
**Pull request by DDinghoya**

### CODE REVIEW

**Comment by lookye** [comment]
@DDinghoya 
Hey, if you can add all the new language strings that were added recently, it should be possible to add korean language in the next release, that will be very soon.

**Comment by iGotenz** [comment]
The owner doesn't want to add any new languages. I'm sorry.

**Comment by DDinghoya** [comment]
> @DDinghoya
> Hey, if you can add all the new language strings that were added recently, it should be possible to add korean language in the next release, that will be very soon.

Thank yor for your mention!!!

Updated this article for the newest language~ :)

**Comment by XorTroll** [comment]
Would you mind updating this translation, along with the other required translation strings? (check other accepted PRs as examples)
I'd like to add Korean support

**Comment by DDinghoya** [comment]
> Would you mind updating this translation, along with the other required translation strings? (check other accepted PRs as examples)
> I'd like to add Korean support

I'm done! :)

**Pull request closed without merging**
