### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by tiliarou**

### CODE REVIEW

**Comment by tiliarou** [comment]
@LittleWhite-tb can you proofread/improve my PR ?
Thanks.

**Comment by goffrier** [comment]
ive tried to clone your fork and type make but it doesnt work

**Comment by goffrier** [comment]
i have built plutonium

**Comment by goffrier** [comment]
learn to code before making merge request kthxbye

**Comment by goffrier** [comment]
and ""Voir les information de la console"," doesnt seem french to me you forgot the "s" to information

**Comment by goffrier** [comment]
ive detected other erros i created a fork let me link it here: https://github.com/goffrier/Tinfoil/blob/master/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp

**Comment by goffrier** [comment]
let me know if there is a error

**Comment by goffrier** [comment]
created a pull request

**Comment by tiliarou** [comment]
Yes there might be a lot of typo so it's good you took the time to proofread it.
Doesn't really matter to know how to "code" for a translation I believe ;)
Yes I shouldn't have had all this commit history but was lazy to squash or start from clean fork...

Just found a typo line 782 "succèsT" instead of succès. Rest looks good to me.

**Comment by goffrier** [comment]
updated my fork

**Comment by goffrier** [comment]
corrected "succèsT"

**Comment by goffrier** [comment]
thanks

**Comment by tiliarou** [comment]
merged your PR

**Comment by goffrier** [comment]
will try to build it now

**Comment by goffrier** [comment]
it still doesnt want to be built

**Comment by goffrier** [comment]
from C:/Tinfoil/Goldleaf/Program/ExeFs/main/Include/gleaf/Goldleaf:25,
                 from C:/Tinfoil/Goldleaf/Program/ExeFs/main/Source/Main.cpp:1:
C:/Tinfoil/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp:608:13: warning: missing terminating " character
             "Lancer,
             ^
C:/Tinfoil/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp:608:13: error: missing terminating " character
             "Lancer,
             ^~~~~~~~
C:/Tinfoil/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp:540:19: error: 'French' is not a member of 'gleaf::Language'
         Language::French,
                   ^~~~~~

**Comment by tiliarou** [comment]
We missed a " at line 608.
And french needs to be declared as a language.

**Comment by goffrier** [comment]
how to declare it?

**Comment by goffrier** [comment]
i got it

**Comment by goffrier** [comment]
i will make a commit soon™

**Comment by tiliarou** [comment]
here: https://github.com/tiliarou/Tinfoil/blob/master/Goldleaf/Program/ExeFs/main/Include/gleaf/Types.hpp

**Comment by goffrier** [comment]
wow thanks

**Comment by goffrier** [comment]
theres also few things to add

**Comment by goffrier** [comment]
im making commits rn

**Comment by goffrier** [comment]
maked a pr
but you cant still make it because of ```c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/8.2.0/../../../../aarch64-none-elf/bin/ld.exe: MainApplication.o: in function `gleaf::ui::MainMenuLayout::webMenuItem_Click()':
C:/Tinfoil/Goldleaf/Program/ExeFs/main/Source/gleaf/ui/MainApplication.cpp:159: undefined reference to `webWifiCreate'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/8.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/Tinfoil/Goldleaf/Program/ExeFs/main/Source/gleaf/ui/MainApplication.cpp:160: undefined reference to `webWifiShow'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/libnx/switch_rules:80: /c/Tinfoil/Goldleaf/Output/Goldleaf.elf] Error 1
make: *** [Makefile:109: Build] Error 2```

**Comment by tiliarou** [comment]
I just built it on ubuntu so I believe the issue might be on your side.
Did you clone the submodule libnx ? did you build libnx goldleaf submodule before building goldleaf itself ?

**Comment by goffrier** [comment]
ive just builted it

**Comment by goffrier** [comment]
so where does it go

**Comment by goffrier** [comment]
oh nvm

**Comment by goffrier** [comment]
how do i activate the french language in gleaf lol

**Comment by goffrier** [comment]
nvm its because its french in the files not Français

**Comment by goffrier** [comment]
i think

**Comment by goffrier** [comment]
so i changed "french" to "francais" still doesnt show french language in gleaf

**Comment by goffrier** [comment]
maybe its because of my custom font

**Comment by goffrier** [comment]
@tiliarou could you look into it?

**Comment by LittleWhite-tb** [comment]
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L556 : should be "Internet" (with the capital letter).

https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L576 : tickets (with the 's' since you should manage several tickets, not just oncce)

https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L564 : "contient plusieurs journaux de tests" ?

https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L580 : "à parcourir"

https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L581 : "sélectionnée"

https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L582 : "apparue"

https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L622 : "Voulez-vous" + space before '?'

https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L620 add a space before '?'

https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L624 add a space before ':'

https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L642 "lancées"

https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L645 add a space before ':'
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L651 add a space before ':*

https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L655 "aux"

https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L666 add a space before ':'
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L660 add a space before ':'
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L680 add a space before ':'
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L687 add a space before ':'
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L695 "Branchez votre console en USB à votre PC"

https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L699 add a space before ':'
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L701 add a space before ':'
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L711 add a space before ':'
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L712 add a space before ':'
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L713 "Titre de base" ?
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L719 add a space before ':'
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L720 add a space before ':'
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L723 add a space before ':'
(I will stop here, for the space before ':' but there are some others)


https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L743 "Informations" ?
https://github.com/XorTroll/Goldleaf/blob/d1f1ee19e86d7d5ae38b591c3c4844f2e15c11e7/Goldleaf/Program/ExeFs/main/Include/gleaf/set/Strings.hpp#L762 "supprimer"

**Comment by goffrier** [comment]
@tiliarou updated the translation please accept my pr

**Comment by XorTroll** [comment]
Oh, nice, lemme check it!

**Pull request merged**
