### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**

### CODE REVIEW

**Comment by ThatNerdyPikachu** [comment]
If we're going to have 2 Linux scripts...

**Comment by LordApple** [comment]
Someone already made a way better solution, and we had two scripts because one was a unix build and the other one is for Linux

**Comment by ThatNerdyPikachu** [comment]
What's the ``better solution``?

**Comment by LordApple** [comment]
https://github.com/XorTroll/Goldleaf/pull/140

**Pull request closed without merging**
