### PR TITLE
Merge OSX and Linux scripts

### PR DESCRIPTION
**Pull request by zkitX**
I decided to combine to two for an easy experience.

I don't have access to a Unix/OSX it would be great for someone to test it, maybe @LordApple since he made the original Generate.sh. Thanks!

I'm pretty sure `#!/usr/bin/env bash` is for best compatibility.

### CODE REVIEW

**Comment by LordApple** [comment]
I won't be able to test it today, but I'll test it as soon as I can

**Comment by LordApple** [comment]
Ok so i have tested it seems to execute everything it should, but hacpackbrew seems to fail the key check for me everything is as it should but i cant get hacpackbrew working

**Comment by ThatNerdyPikachu** [comment]
*hacbrewpack

And what do you mean by "fail the key check?"

**Comment by azoreseuropa** [comment]
Where can I get it for my macOS, please ?

**Pull request closed without merging**
