### PR TITLE
removed piracy features

### PR DESCRIPTION
**Pull request by blawar**
for the cleansing of the soul

### CODE REVIEW

**Comment by EliseZeroTwo** [comment]
I think this is a very good way forward for the project. Piracy is a sin, this stops users using Goldleaf for ill-intent. Unless you think that Goldleaf is a piracy tool then feel free to not merge the commit, I support you either way @XorTroll.

**Comment by XorTroll** [comment]
Fuck you.

**Comment by EliseZeroTwo** [comment]
Please watch your language. It is a sin to swear. It's ok though, Jesus forgives all that seek his forgiveness. I recommend seeking out a church nearby to cleanse yourself of your sins. You can confess all without any judgement.

**Comment by desertcat12** [comment]
this would be a really nice change
dont see why this white light homebrew program should be so heavily bloated with piracy features

**Pull request closed without merging**
