### PR TITLE
add Chinese simplified translation 

### PR DESCRIPTION
**Pull request by WanderMax**
make the first version of Chinese simplified translation.
I'm not sure the language code zh_cn is right or not for NS system, if not right please correct it.
thanks.

### CODE REVIEW

**Comment by iGotenz** [comment]
I don't think the unpatched Switches were ever sold in China.

**Comment by WanderMax** [comment]
I can buy hk or jap version, and change system language.

**Comment by leemove** [comment]
@iGotenz   unpatched Switches were sold more than 50,0000  on [Taobao(chinese ebay)](https://www.taobao.com/) in china.

**Comment by chenxuuu** [comment]
here is switch's website in China
https://www.nintendoswitch.com.cn/

when will this pr be marged?

**Pull request closed without merging**
