### PR TITLE
Let USB installation script accept multiple NSP path, files and patterns

### PR DESCRIPTION
**Pull request by jbollacke**
```
usb_install_py.py C:/somepath C:/someotherpath
usb_install_py.py C:/somepath/homebrew*.nsp
usb_install_py.py C:/somepath/homebrew1.nsp C:/somepath/homebrew2.nsp C:/someotherpath/homebrewN.nsp
```

Also supports dragging an NSP onto the python script if pyhon execution is correctly setup on windows.

### CODE REVIEW

**Comment by XorTroll** [comment]
Does this work ok?

**Comment by jbollacke** [comment]
Well I have only tested all three options on Win 10 x64 + Python v3.7.0.

**Comment by co5mo** [comment]
drag and drop works for me

**Comment by co5mo** [comment]
tested but got corupted installation using latest tinfoil and this py

**Pull request closed without merging**
