### PR TITLE
Fix the compilation system

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**

### CODE REVIEW

**Comment by XorTroll** [comment]
And the purpose of this "fix" is...?

**Comment by ThatNerdyPikachu** [comment]
:pain: wrong term, I suppose.

There is no point to copy the NSO to the exefs while building the NRO, only the PFS0 actually requires it.

You'd also need to run the NRO script before the PFS0 one, so that I "fixed?"

P.S. @LordApple, be quiet.

**Comment by XorTroll** [comment]
Well true, the NRO one builds the NRO and the NSO, so it's easier to merge'em

**Comment by XorTroll** [comment]
I'm rewriting other shit right now, already merged both batch scripts. I'll push everything in a commit in a few minutes.

**Pull request closed without merging**
